services:
  stork-db:
    restart: unless-stopped
    image: postgres:18
    shm_size: 128mb
    environment:
      - POSTGRES_USER=stork
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=stork
    volumes: 
      - ./postgres:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stork"]
      interval: 5s
      timeout: 5s
      retries: 5

  stork-server:
    restart: unless-stopped
    build:
      context: ./stork-server
    ports:
      - "${HOST_IP}:8087:8080"
    environment:
      - STORK_DATABASE_HOST=stork-db
      - STORK_DATABASE_NAME=stork
      - STORK_DATABASE_USER=stork
      - STORK_DATABASE_PASSWORD=${DB_PASSWORD}
    depends_on:
      stork-db:
        condition: service_healthy
  # no ports needed cause network_mode: hsot
  kea-dhcp:
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    build: ./dhcp-server
    network_mode: "host"
    environment:
      - STORK_AGENT_SERVER_URL=http://localhost:8087
      - STORK_AGENT_HOST=${HOST_IP}
      - INTERFACES=${INTERFACES}
    volumes:
      - ./stork-agent-data:/var/lib/stork-agent
      - ./kea-config:/etc/kea
      - ./kea-sockets:/var/run/kea
      - ./kea-db:/var/lib/kea
    depends_on:
      - stork-server
