[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:kea-dhcp4]
command=/bin/sh -c "sleep 5 && exec /usr/sbin/kea-dhcp4 -c /etc/kea/kea-dhcp4.conf"
autostart=true
startsecs=10
autorestart=true

[program:stork-agent]
command=/usr/bin/stork-agent
autostart=true
autorestart=true
