[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:kea-dhcp4]
command=/usr/sbin/kea-dhcp4 -c /etc/kea/kea-dhcp4.conf
autostart=true
autorestart=true

[program:stork-agent]
command=/usr/bin/stork-agent
autostart=true
autorestart=true
